apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert --volumes hostPath
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: info3
  name: info3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: info3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert --volumes hostPath
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: info3
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-2.mongo.default.svc.cluster.local:27017/mydatabase
          image: registry.hub.docker.com/radudob/pad_info
          name: info3
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
