apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert --volumes hostPath
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  type: LoadBalancer
  ports:
    - name: "6969"
      port: 6969
      targetPort: 6969
  selector:
    io.kompose.service: proxy
status:
  loadBalancer: {}
